export const palette = {
    light: {
        colors: {
            primary: {
                main: '#5271ff',
                light: '#eaefff',
                dark: '#2c46cc',
                contrastText: '#ffffff',
            },
            secondary: {
                main: '#dc004e',
                light: '#ff5c8d',
                dark: '#9a0036',
                contrastText: '#ffffff',
            },
            error: {
                main: '#f44336',
                light: '#e57373',
                dark: '#d32f2f',
                contrastText: '#ffffff',
            },
            warning: {
                main: '#ff9800',
                light: '#ffb74d',
                dark: '#f57c00',
                contrastText: '#000000',
            },
            info: {
                main: '#2196f3',
                light: '#64b5f6',
                dark: '#1976d2',
                contrastText: '#ffffff',
            },
            success: {
                main: '#4caf50',
                light: '#81c784',
                dark: '#388e3c',
                contrastText: '#ffffff',
            },
            grey: {
                50: '#fafafa',
                100: '#f5f5f5',
                200: '#eeeeee',
                300: '#e0e0e0',
                400: '#bdbdbd',
                500: '#9e9e9e',
                600: '#757575',
                700: '#616161',
                800: '#424242',
                900: '#212121',
            },
            text: {
                primary: '#32425f',
                secondary: '#66758f',
                disabled: '#a0aec0',
            },
            background: {
                default: '#ffffff',
                paper: '#f7fafc',
                sidebar: '#f3f5f8',
            },
            action: {
                active: 'rgba(0, 0, 0, 0.54)',
                hover: 'rgba(0, 0, 0, 0.04)',
                selected: 'rgba(0, 0, 0, 0.08)',
                disabled: 'rgba(0, 0, 0, 0.26)',
                disabledBackground: 'rgba(0, 0, 0, 0.12)',
            },
            border: {
                main: '#e2e8f0',
                light: '#edf2f7',
                dark: '#cbd5e0',
            },
            status: {
                inProgress: '#3f51b5',
                failed: '#f44336',
                passed: '#4caf50',
                blocked: '#ff9800',
                retest: '#2196f3',
                skipped: '#9e9e9e',
                invalid: '#9c27b0',
            },
        },
    },
    dark: {
        colors: {
            primary: {
                main: '#5271ff',
                light: '#4b5bab',
                dark: '#303f9f',
                contrastText: '#ffffff',
            },
            secondary: {
                main: '#f48fb1',
                light: '#f6a5c0',
                dark: '#bf5f82',
                contrastText: '#000000',
            },
            error: {
                main: '#f44336',
                light: '#e57373',
                dark: '#d32f2f',
                contrastText: '#ffffff',
            },
            warning: {
                main: '#ff9800',
                light: '#ffb74d',
                dark: '#f57c00',
                contrastText: '#000000',
            },
            info: {
                main: '#2196f3',
                light: '#64b5f6',
                dark: '#1976d2',
                contrastText: '#ffffff',
            },
            success: {
                main: '#4caf50',
                light: '#81c784',
                dark: '#388e3c',
                contrastText: '#ffffff',
            },
            grey: {
                50: '#fafafa',
                100: '#f5f5f5',
                200: '#eeeeee',
                300: '#e0e0e0',
                400: '#bdbdbd',
                500: '#9e9e9e',
                600: '#757575',
                700: '#616161',
                800: '#424242',
                900: '#212121',
            },
            text: {
                primary: '#e2e8f0',
                secondary: '#a0aec0',
                disabled: '#718096',
            },
            background: {
                default: '#121212',
                paper: '#1a202c',
                sidebar: '#2d3748',
            },
            action: {
                active: 'rgba(255, 255, 255, 0.7)',
                hover: 'rgba(255, 255, 255, 0.08)',
                selected: 'rgba(255, 255, 255, 0.16)',
                disabled: 'rgba(255, 255, 255, 0.3)',
                disabledBackground: 'rgba(255, 255, 255, 0.12)',
            },
            border: {
                main: '#2d3748',
                light: '#4a5568',
                dark: '#1a202c',
            },
            status: {
                inProgress: '#3f51b5',
                failed: '#f44336',
                passed: '#4caf50',
                blocked: '#ff9800',
                retest: '#2196f3',
                skipped: '#9e9e9e',
                invalid: '#9c27b0',
            },
        },
    },
};
